import hashlib

def encrypt_this_string(input_string):
    """Generate SHA-1 hash for the given input string."""
    sha1_hash = hashlib.sha1(input_string.encode())  # Encode string and compute hash
    return sha1_hash.hexdigest()  # Convert hash to hexadecimal format

if __name__ == "__main__":
    print("------------ HashCode Generated by SHA-1 -----------")

    # Taking dynamic input
    text1 = input("\nEnter first text: ")
    print(f"{text1} : {encrypt_this_string(text1)}")

    text2 = input("\nEnter second text: ")
    print(f"{text2} : {encrypt_this_string(text2)}")
